version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: portfolio-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123

  backend:
    build: ./server
    container_name: portfolio-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/portfolio?authSource=admin
      - JWT_SECRET=your_jwt_secret_here
      - CLOUDINARY_CLOUD_NAME=your_cloudinary_name
      - CLOUDINARY_API_KEY=your_cloudinary_api_key
      - CLOUDINARY_API_SECRET=your_cloudinary_api_secret
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build: ./client
    container_name: portfolio-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mongodb_data: